### To generate the output file to partially incorporate in the README.md,
### Execute this command in the root of this project:
# terraform-docs .

formatter: "markdown table" # this is required

version: "~> 0.19"

sections:
  hide: []
  show: []

content: |-
  <!-- markdownlint-disable MD033 -->
  {{ .Requirements }}

  {{ .Resources }}

  <!-- markdownlint-disable MD013 -->
  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Modules }}

output:
  file: README.md

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true