### To generate the output file to partially incorporate in the README.md,
### Invocation example:
### Update README.md of example/01-basic
# terraform-docs ./examples/01-basic --config ./examples/terraform-docs.yml

formatter: "markdown document" # this is required

version: "~> 0.19"

sections:
  hide: []
  show: []

content: |-

  {{ .Header }}

  ```hcl
  {{ include "main.tf" }}
  ```
  {{ .Outputs }}

output:
  file: README.md
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true