#name: "Tag and release terraform module"

#on:
#  push:
#    branches:
#      - main

#jobs:
#  tag-and-release:
#    uses: dsb-norge/github-actions-terraform/.github/workflows/terraform-module-release.yaml@v0
#    secrets: inherit
#    permissions:
#        contents: write  # required for checkout action.
#        pull-requests: write # required for commenting on PR
